/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/routes/__root";
import { Route as AppRouteImport } from "./app/routes/_app";
import { Route as AppDashboardRouteImport } from "./app/routes/_app/dashboard";
import { Route as AppSettingsRouteImport } from "./app/routes/_app/settings";
import { Route as PublicRouteImport } from "./app/routes/_public";
import { Route as PublicAboutRouteImport } from "./app/routes/_public/about";
import { Route as PublicContactRouteImport } from "./app/routes/_public/contact";
import { Route as PublicIndexRouteImport } from "./app/routes/_public/index";
import { Route as PublicLoginRouteImport } from "./app/routes/_public/login";
import { Route as PublicPricingRouteImport } from "./app/routes/_public/pricing";
import { Route as PublicRegisterRouteImport } from "./app/routes/_public/register";

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PublicRoute,
} as any);
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => PublicRoute,
} as any);
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => PublicRoute,
} as any);
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any);
const PublicContactRoute = PublicContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => PublicRoute,
} as any);
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => PublicRoute,
} as any);
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof PublicIndexRoute;
  "/dashboard": typeof AppDashboardRoute;
  "/settings": typeof AppSettingsRoute;
  "/about": typeof PublicAboutRoute;
  "/contact": typeof PublicContactRoute;
  "/login": typeof PublicLoginRoute;
  "/pricing": typeof PublicPricingRoute;
  "/register": typeof PublicRegisterRoute;
}
export interface FileRoutesByTo {
  "/": typeof PublicIndexRoute;
  "/dashboard": typeof AppDashboardRoute;
  "/settings": typeof AppSettingsRoute;
  "/about": typeof PublicAboutRoute;
  "/contact": typeof PublicContactRoute;
  "/login": typeof PublicLoginRoute;
  "/pricing": typeof PublicPricingRoute;
  "/register": typeof PublicRegisterRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteWithChildren;
  "/_public": typeof PublicRouteWithChildren;
  "/_app/dashboard": typeof AppDashboardRoute;
  "/_app/settings": typeof AppSettingsRoute;
  "/_public/about": typeof PublicAboutRoute;
  "/_public/contact": typeof PublicContactRoute;
  "/_public/login": typeof PublicLoginRoute;
  "/_public/pricing": typeof PublicPricingRoute;
  "/_public/register": typeof PublicRegisterRoute;
  "/_public/": typeof PublicIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/settings"
    | "/about"
    | "/contact"
    | "/login"
    | "/pricing"
    | "/register";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/settings"
    | "/about"
    | "/contact"
    | "/login"
    | "/pricing"
    | "/register";
  id:
    | "__root__"
    | "/_app"
    | "/_public"
    | "/_app/dashboard"
    | "/_app/settings"
    | "/_public/about"
    | "/_public/contact"
    | "/_public/login"
    | "/_public/pricing"
    | "/_public/register"
    | "/_public/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public/": {
      id: "/_public/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/register": {
      id: "/_public/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof PublicRegisterRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/pricing": {
      id: "/_public/pricing";
      path: "/pricing";
      fullPath: "/pricing";
      preLoaderRoute: typeof PublicPricingRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/login": {
      id: "/_public/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof PublicLoginRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/contact": {
      id: "/_public/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof PublicContactRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_public/about": {
      id: "/_public/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof PublicAboutRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_app/settings": {
      id: "/_app/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AppSettingsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/dashboard": {
      id: "/_app/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute;
  AppSettingsRoute: typeof AppSettingsRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute;
  PublicContactRoute: typeof PublicContactRoute;
  PublicLoginRoute: typeof PublicLoginRoute;
  PublicPricingRoute: typeof PublicPricingRoute;
  PublicRegisterRoute: typeof PublicRegisterRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
